Td dis consumer
marfrede/o2m-api pull request #17
Opened 2021-01-25 15:50 UTC by Marv05

- phpunit.xml and config/database.php were added to gitignore
- First Unit Test were introduced/written/implemented/executed
- isConsumerOf, isManagerOf, isOwnerOf were refactored into UserRepo

2021-02-02 17:46 UTC, marfrede requested changes

2021-02-02 17:46 UTC, marfrede commented on app/Repositories/UserRepository.php
> +    }
Ich würde doch vorschlagen, immer das Repo mit der möglichst niedrigsten Hierarchiestufe zu wählen, damit möglichst vielen andere Repos diese Methode zur Verfügung steht.
Das wäre dann das OpenPermissionRepo.

2021-02-02 17:46 UTC, marfrede commented on app/Repositories/UserRepository.php
> +    }
Diese Methode könnte dann am besten im LicenseRepo liegen und statt getManagerOfLock dann im Stile der isConsumerOf function dann getLicensesForManagerAndLock nutzen, die es glaube ich noch nicht gibt..
Wir müssen aufpassen, dass kein Chaos in den Repos entsteht.

2021-02-02 17:46 UTC, marfrede commented on app/Repositories/UserRepository.php
> +    }
Diese Methode kann hier bleiben denke ich..

2021-02-02 17:53 UTC, marfrede requested changes
Ein paar Fragen müssen noch geklärt werden:
* Bezüglich der isBlaOf Methoden
* Wäre es sinnvoll config/database.example.php und phpunit.example.xml zu haben?

2021-02-02 17:57 UTC, Marv05 commented on .gitignore
> +/config/database.php
die sind ja in deinem Projekt

2021-02-02 18:06 UTC, Marv05 commented on app/Repositories/UserRepository.php
> +use phpDocumentor\Reflection\Types\Boolean;
Ja, stimmt.

2021-02-02 18:14 UTC, Marv05 commented on app/Repositories/UserRepository.php
> +    }
Ich sehe da irgednwie nur die letzten 4 Zeilen von isConsumerOf.
Der Vorteil von den Hierarchiestufen war: Wegen den Hierarchiestufen muss man weniger Repos injizieren ne?

Ich muss sagen, dass ich jetzt so nicht aus dem Kopf weiß, wo der beste Ort wäre... Wenn du einen besseren Ort für die hast, würde ich dir da jetzt einfach blind vertrauen und du könntest dann das refactoren also die methoden verschieben

2021-02-02 18:18 UTC, Marv05 commented on app/Repositories/UserRepository.php
> +    }
Ich weiß noch, dass mir aufgefallen ist, dass da teils sehr ähnliche Methoden waren...

Kein Chaos wäre gut...

Ansonsten habe ich da kein Problem mit, wenn wirs nochmal Refactoren würden!

2021-02-02 18:18 UTC, Marv05 commented on app/Repositories/UserRepository.php
> +    }
Jo...

2021-02-04 15:20 UTC, marfrede commented on app/Repositories/UserRepository.php
> +    }
delegieren

2021-02-04 18:10 UTC, merged